/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.30                          *
*        Compiled Jul  1 2015, 10:50:32                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END
#include "HomeworkGUI.h"
#include "EmWinHZFont.h"
#include "buttonbmp.h"
#include "ImageDisplay.h"
#include "usbh_app.h"
#include "PageHandle.h"
#include "jpegdisplay.h"
#include "camera_app.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0    (GUI_ID_USER + 0x00)
#define ID_MULTIPAGE_0    (GUI_ID_USER + 0x01)

GUI_BITMAP buttonbmp_tab[2];
WM_HWIN WM_Camera;
// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

/*********************************************************************
*
*       Dialog resource
*
*  These tables contain the information required to create the dialogs.
*  It has been created manually, but could also be created by the GUIBuilder.
struct GUI_WIDGET_CREATE_INFO_struct {
  GUI_WIDGET_CREATE_FUNC * pfCreateIndirect;
  const char             * pName;            // Text ... Not used on all widgets
  I16                      Id;               // ID ... should be unique in a dialog
  I16                      x0;               // x position
  I16                      y0;               // y position
  I16                      xSize;            // x size
  I16                      ySize;            // y size
  U16                      Flags;            // Widget specific create flags (opt.)
  I32                      Para;             // Widget specific parameter (opt.)
  U32                      NumExtraBytes;    // Number of extra bytes usable with <WIDGET>_SetUserData & <WIDGET>_GetUserData
};
*/
//470*745
static const GUI_WIDGET_CREATE_INFO _aDialogCreatePage1[] = {
//pfCreateIndirect             pName     Id                   x0    y0     xSize    ySize   Flags                      Para       NumExtraBytes
  { WINDOW_CreateIndirect,    "Dialog",  0,                   0,    0,     470,     780,    FRAMEWIN_CF_MOVEABLE                        },
  { IMAGE_CreateIndirect,     "Image",   GUI_ID_IMAGE0,       0,    0,     470,     780,    IMAGE_CF_AUTOSIZE,            0,           0 },
  { TEXT_CreateIndirect,      "",        GUI_ID_TEXT0,        200,   730,    100,     16,   TEXT_CF_LEFT                                },
};  
static const GUI_WIDGET_CREATE_INFO _aDialogCreatePage2[] = {
//pfCreateIndirect             pName     Id                   x0    y0     xSize    ySize   Flags                      Para       NumExtraBytes
  { WINDOW_CreateIndirect,    "Dialog",  0,                   0,    0,     470,     780,    FRAMEWIN_CF_MOVEABLE                        },
  { IMAGE_CreateIndirect,     "Image",   GUI_ID_IMAGE1,       0,    0,     470,     780,    IMAGE_CF_AUTOSIZE,            0,           0 },
 // { BUTTON_CreateIndirect,      "",      GUI_ID_BUTTON1,      180,  600,   120,     120,    0                                },
};  
static const GUI_WIDGET_CREATE_INFO _aDialogCreatePage3[] = {
//pfCreateIndirect             pName     Id                   x0    y0     xSize    ySize   Flags
  { WINDOW_CreateIndirect,    "Dialog",  0,                   0,    0,     470,     700,    FRAMEWIN_CF_MOVEABLE },
  { BUTTON_CreateIndirect,    "",        GUI_ID_BUTTON0,      180,  10,    110,     40,     0},
  { TEXT_CreateIndirect,      "",        GUI_ID_TEXT2,        50,   20,    100,     1,     TEXT_CF_LEFT },
  { LISTBOX_CreateIndirect,   "",        GUI_ID_LISTVIEW0,    50,   60,    200,     500,    0 },
};

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "Framewin", ID_FRAMEWIN_0, 0, 0, 480, 800, 0, 0x64, 0 },
  { MULTIPAGE_CreateIndirect, "Multipage", ID_MULTIPAGE_0, 0, 0, 470, 770, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

static void _cbDialogPage1(WM_MESSAGE * pMsg) {
	WM_HWIN hItem;
	WM_HWIN hDlg;
	int     NCode;
	int     Id;

	hDlg = pMsg->hWin;
	switch (pMsg->MsgId) {
	case WM_INIT_DIALOG:	  
	{
		printf("init page 1\r\n");
	
		//初始化TEXT
		hItem = WM_GetDialogItem(hDlg, GUI_ID_TEXT0);
		TEXT_SetFont(hItem,&GUI_FontHZ16);
		TEXT_SetText(hItem,"共   图片");
	}
	break;
	case WM_NOTIFY_PARENT:
	{	
		Id    = WM_GetId(pMsg->hWinSrc);
		NCode = pMsg->Data.v;	
		printf("notify from page 1,ID = %d, NCode = %d\r\n",Id, NCode);
		switch(Id) 
		{
			case GUI_ID_IMAGE0: 
			{
				hItem = WM_GetDialogItem(pMsg->hWin, GUI_ID_IMAGE0);
				switch(NCode) 
				{
					case WM_NOTIFICATION_CLICKED:
					// USER START (Optionally insert code for reacting on notification message)
					// USER END
					break;
					case WM_NOTIFICATION_RELEASED:
					{
					}
					break;
					case WM_NOTIFICATION_MOVED_OUT:
					// USER START (Optionally insert code for reacting on notification message)
					// USER END
					break;
					case WM_NOTIFICATION_VALUE_CHANGED:
					// USER START (Optionally insert code for reacting on notification message)
					// USER END
					break;	
				}
			} 
			break;

		}
	}
	break;
	default:
		WM_DefaultProc(pMsg);
	}
}
static void _cbDialogPage2(WM_MESSAGE * pMsg) {
	WM_HWIN hItem;
	WM_HWIN hDlg;
	int     NCode;
	int     Id;

	hDlg = pMsg->hWin;
	switch (pMsg->MsgId) {
	case WM_INIT_DIALOG:	  
	{
		printf("init page 1\r\n");
	
		//初始化BUTTON
//		hItem = WM_GetDialogItem(pMsg->hWin, GUI_ID_BUTTON1);
//		BUTTON_SetBitmapEx(hItem,0,&bmcamera2,0,0);
//		BUTTON_SetText(hItem, "");
	}
	break;
	case WM_PAINT:	  
	{

		//hItem = WM_GetDialogItem(hDlg, GUI_ID_IMAGE1);
	    IMAGE_SetBitmap(WM_Camera,&bm2_c);
		Start_Camera();
	
	}
	break;
	case WM_NOTIFY_PARENT:
	{	
		Id    = WM_GetId(pMsg->hWinSrc);
		NCode = pMsg->Data.v;	
		printf("notify from page 1,ID = %d, NCode = %d\r\n",Id, NCode);
		switch(Id) 
		{
			case GUI_ID_IMAGE0: 
			{
				hItem = WM_GetDialogItem(pMsg->hWin, GUI_ID_IMAGE0);
				switch(NCode) 
				{
					case WM_NOTIFICATION_CLICKED:
					// USER START (Optionally insert code for reacting on notification message)
					// USER END
					break;
					case WM_NOTIFICATION_RELEASED:
					{
					}
					break;
					case WM_NOTIFICATION_MOVED_OUT:
					// USER START (Optionally insert code for reacting on notification message)
					// USER END
					break;
					case WM_NOTIFICATION_VALUE_CHANGED:
					// USER START (Optionally insert code for reacting on notification message)
					// USER END
					break;	
				}
			} 
			break;

		}
	}
	break;
	default:
		WM_DefaultProc(pMsg);
	}
}
static void _cbDialogPage3(WM_MESSAGE * pMsg) {
	WM_HWIN hItem;
	WM_HWIN hDlg;
	int     NCode;
	int     Id;
	static u8 ButtonFlag=0;
	
	hDlg = pMsg->hWin;
	switch (pMsg->MsgId) {
	case WM_INIT_DIALOG:	  
	{
		//初始化TEXT
		hItem = WM_GetDialogItem(hDlg, GUI_ID_TEXT0);
		TEXT_SetFont(hItem,&GUI_FontHZ16);
		TEXT_SetText(hItem,"无线局域网");

		//初始化BUTTON
		hItem = WM_GetDialogItem(pMsg->hWin, GUI_ID_BUTTON0);
		BUTTON_SetBitmapEx(hItem,0,&buttonbmp_tab[0],0,0);
		BUTTON_SetText(hItem, "");
		
		//初始化列表
		hItem = WM_GetDialogItem(pMsg->hWin, GUI_ID_LISTVIEW0);
		LISTBOX_SetFont(hItem,&GUI_FontHZ16);
		LISTBOX_AddString(hItem,"请打开WIFI开关");
		
	}
	break;
	case WM_NOTIFY_PARENT:
	{	
		Id    = WM_GetId(pMsg->hWinSrc);
		NCode = pMsg->Data.v;	
		switch(Id) 
		{
			case GUI_ID_BUTTON0: //BUTTON_0的通知代码，控制LED1
			{
				hItem = WM_GetDialogItem(pMsg->hWin, GUI_ID_BUTTON0);
				switch(NCode) 
				{
					case WM_NOTIFICATION_CLICKED:
					break;
					case WM_NOTIFICATION_RELEASED: //按钮被按下并释放
					{
						ButtonFlag=~ButtonFlag;
						BUTTON_SetBitmapEx(hItem,BUTTON_BI_UNPRESSED,ButtonFlag?&buttonbmp_tab[1]:&buttonbmp_tab[0],0,0);
					}						
					break;	
				}
			}
			break;

		}
	}
	break;
	default:
		WM_DefaultProc(pMsg);
	}
}

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
	WM_HWIN hItem;
	WM_HWIN hDialog;
	int     NCode;
	int     Id;
	char PageIndex;
	PAGEHANDLE_PARA para;
	switch (pMsg->MsgId) {
	case WM_INIT_DIALOG:
	{
		printf("init multipage \r\n");
		//
		// 初始化框架
		//
		hItem = pMsg->hWin;
		FRAMEWIN_SetText(hItem, "作业查看提交系统");
		FRAMEWIN_SetTitleHeight(hItem, 25);
		FRAMEWIN_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		FRAMEWIN_SetFont(hItem, &GUI_FontHZ24);
		//
		// 初始化多页显示工具
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_MULTIPAGE_0);
		
		//第一页
		hDialog = GUI_CreateDialogBox(_aDialogCreatePage1, GUI_COUNTOF(_aDialogCreatePage1), _cbDialogPage1, WM_UNATTACHED, 0, 0);
		MULTIPAGE_AddPage(hItem, hDialog, "查看作业");
		
		hDialog = GUI_CreateDialogBox(_aDialogCreatePage2, GUI_COUNTOF(_aDialogCreatePage2), _cbDialogPage2, WM_UNATTACHED, 0, 0);
		MULTIPAGE_AddPage(hItem, hDialog, "提交作业");
		
		//第三页
		hDialog = GUI_CreateDialogBox(_aDialogCreatePage3, GUI_COUNTOF(_aDialogCreatePage3), _cbDialogPage3, WM_UNATTACHED, 0, 0);
		MULTIPAGE_AddPage(hItem, hDialog, "系统设置");
		CurrentPage=2;//当前页面
		PreviousPage=2;//之前页面
		
//		PageIndex=MULTIPAGE_GetSelection (hItem); 
//		PageHnadle_main(PageIndex);
		MULTIPAGE_SetTabWidth(hItem,100,0); //not supported for v5.24		
		MULTIPAGE_SetTabWidth(hItem,100,1); //not supported for v5.24
		MULTIPAGE_SetTabWidth(hItem,100,2); //not supported for v5.24
		MULTIPAGE_SetFont(hItem,&GUI_FontHZ16);
		
		WM_Camera  = WM_GetDialogItem(hItem, GUI_ID_IMAGE1);
		// USER START (Optionally insert additional code for further widget initialization)
		// USER END
	}
	break;
	case WM_NOTIFY_PARENT:
	{
		Id    = WM_GetId(pMsg->hWinSrc);
		NCode = pMsg->Data.v;
		hItem = WM_GetDialogItem(pMsg->hWin, ID_MULTIPAGE_0);
		printf("notify from  multipage Id=%d,NCode=%d\r\n",Id,NCode);
		switch(Id) {
		case ID_MULTIPAGE_0: // Notifications sent by 'Multipage'
		  switch(NCode) {
		  case WM_NOTIFICATION_CLICKED:
			// USER START (Optionally insert code for reacting on notification message)
			// USER END
			break;
		  case WM_NOTIFICATION_RELEASED:
			// USER START (Optionally insert code for reacting on notification message)
			// USER END
			break;
		  case WM_NOTIFICATION_MOVED_OUT:
			// USER START (Optionally insert code for reacting on notification message)
			// USER END
			break;
		  case WM_NOTIFICATION_VALUE_CHANGED:		
		  {
				// 此时的hItem是  Multipage
				PageIndex=MULTIPAGE_GetSelection (hItem);
				// 此时的hItem是  IMAGE0
				hItem = WM_GetDialogItem(hItem, GUI_ID_IMAGE0);
				para.page= PageIndex;
				para.hItem = hItem;

				PageHnadle_main(&para);
			}
			break;
		  // USER START (Optionally insert additional code for further notification handling)
		  // USER END
		  }
		  break;
		// USER START (Optionally insert additional code for further Ids)
		// USER END
		}
	}
	break;
	// USER START (Optionally insert additional message handling)
	// USER END
	default:
	WM_DefaultProc(pMsg);
	break;
	}
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateFramewin
*/

WM_HWIN CreateFramewin(void) {
	WM_HWIN hWin;
	buttonbmp_tab[0]=bmBUTTONOFF;
	buttonbmp_tab[1]=bmBUTTONON;
	
	hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
	return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
